language: php

services:
    - mysql
    - rabbitmq
    - redis-server

php:
    - 5.6
    - 7.0
    - 7.1

sudo: false

before_script:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - travis_retry composer self-update
    - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction
    - mysql -e 'DROP DATABASE IF EXISTS adminerng_test;'
    - mysql -e 'CREATE DATABASE adminerng_test;'

script:
    - mkdir -p log
    - mkdir -p temp
    - mkdir -p build/logs
    - php vendor/bin/phpcs app tests --standard=PSR2 -n
    - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
